# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: tolgazorlu17@gmail.com
author_name: tolgazorlu
contract_name: algomap
preset_name: production
project_name: algomap-contracts

