name: Pull Request validation

on: [pull_request]


jobs:
  algomap-contracts-ci:
    name: Run algomap-contracts validation
    uses: ./.github/workflows/algomap-contracts-ci.yaml

  algomap-frontend-ci:
    name: Run algomap-frontend validation
    uses: ./.github/workflows/algomap-frontend-ci.yaml

